baseurl = "/"
title = "Cybervattam"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "JSON"]

[security]
allowContent = ['^text/.*$']
enableInlineShortcodes = true
[security.funcs]
getenv = ['^HUGO_','CONTEXT','BUILD_PRODUCTION']

[languages.en]
weight = 1
label = "English"
contentDir = 'content.en'

[languages.ta]
weight = 2
label = "தமிழ்"
contentDir = 'content.ta'

[languages.hi]
weight = 3
label = "हिन्दी"
contentDir = 'content.hi'

[languages.ml]
weight = 4
label = "മലയാളം"
contentDir = 'content.ml'

[languages.te]
weight = 5
label = "తెలుగు"
contentDir = 'content.te'

[languages.kn]
weight = 6
label = "ಕನ್ನಡ"
contentDir = 'content.kn'


# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
[markup.goldmark.renderer]
  unsafe= true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = true
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[taxonomies]
  tag = "tags"